Adding in more statistics into the client
EasyNetQ/EasyNetQ.Management.Client pull request #119
Opened 2019-06-12 21:43 UTC by benrjm

These are extra statistics available in the Rabbit API and they are useful in monitoring how long a message has been in the queue and some additional ACK stats

2019-12-06 18:44 UTC, AaronEshbach commented
I was about to make PR for the same changes (the ACK Rate/stats), as I have forked the repository to add this myself.  This is a really useful statistic if you have subscribers doing manual acknowledgments!

2021-03-15 19:04 UTC, micdenny requested changes
thank for the PR, please check the comment

2021-03-15 19:04 UTC, micdenny commented on Source/EasyNetQ.Management.Client/Model/MessageStats.cs
> +        public Int64 Ack { get; set; }
please use `long` instead of `Int64`

2021-03-16 09:41 UTC, zidad approved these changes

2022-12-11 23:48 UTC, Pliner commented
Fixed in #173

2022-12-11 23:48 UTC, closed without merging