Feature/add ha sync batch size
EasyNetQ/EasyNetQ.Management.Client pull request #126
Opened 2019-08-30 20:04 UTC by ArgTang

#125 

* Adding property to PolicyDefinition to support setting sync batch size 
* VS changed indenting based on .editorconfig
* Fix Docker connection, for running tests
https://github.com/microsoft/Docker.DotNet/issues/397#issuecomment-500186485

2019-08-30 20:39 UTC, ArgTang commented
@zidad I am not too familiar with travis, do you have an idea for what could be wrong?

2019-09-02 13:29 UTC, zidad commented
I'm not sure if we should keep the travis build in there. Seems a bit overkill now with .NET core. @luigiberrettini knows about this? Can we just get rid of the travis build or did the changes in the PR break the build?

2019-09-02 13:31 UTC, zidad commented
@ArgTang what was the need for the changes in the docker configuration, before it seemed to run fine on travis, can you undo that and see if it works?

2019-09-02 13:35 UTC, ArgTang commented
@zidad i can try when i get home. The reason for the change was that i was not able to run any of the tests on my local machine.

2019-09-02 14:20 UTC, luigiberrettini commented
Having AppVeyor and Travis CI allows to build code and run tests against Docker containers on both Windows and Linux.
It would be nice to also do so on OS X but Docker support for Travis CI matrix builds was missing at the moment I created the scripts (I didn't check if this is still the case).

2019-09-08 17:40 UTC, ArgTang commented
@zidad reverted test running changes.

2021-03-15 18:39 UTC, micdenny requested changes
thank you for this PR, please check the comments

2021-03-15 18:39 UTC, micdenny commented on Source/EasyNetQ.Management.Client.IntegrationTests/ManagementClientTests.cs
> +    [Integration]
please fix all this spaces? did you add tabs instead? please revert on what was before, to see only your changes

2021-03-15 18:39 UTC, micdenny commented on Source/EasyNetQ.Management.Client.Tests/Model/PolicySerializationTests.cs
> +}
what's the change here?

2021-03-15 18:39 UTC, micdenny commented on Source/EasyNetQ.Management.Client.sln
> +
what's the change here?

2021-03-15 18:47 UTC, micdenny commented on Source/EasyNetQ.Management.Client.IntegrationTests/ManagementClientTests.cs
> +    [Integration]
maybe it's some spacing fixed after, BTW please resolve the conflict

2022-12-11 23:35 UTC, Pliner commented
Fixed in #172

2022-12-11 23:35 UTC, closed without merging